version: '3'

services:
  client-configs-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19346jaidj
      POSTGRES_DB: ClientConfigs
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C.UTF-8"
    ports:
      - "2345:5432" 
    volumes:
      - client_configs_pgdata:/var/lib/postgresql/data 
      - ./Dumps/ClientConfigsData.sql:/docker-entrypoint-initdb.d/ClientConfigsData.sql

  notifications-exchange-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19346jaidj
      POSTGRES_DB: NotificationsExchange
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C.UTF-8"
    ports:
      - "2346:5432" 
    volumes:
      - notifications_exchange_pgdata:/var/lib/postgresql/data 
      - ./Dumps/NotificationsExchange.sql:/docker-entrypoint-initdb.d/NotificationsExchange.sql

volumes:
  client_configs_pgdata:
  notifications_exchange_pgdata: