version: '3'

services:
  db-client-configs:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19346jaidj
      POSTGRES_DB: ClientConfigs
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C.UTF-8"
    ports:
      - "2345:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./ClientConfigsData.sql:/docker-entrypoint-initdb.d/ClientConfigsData.sql
volumes:
  pgdata: